### DISCUSSION TITLE
Password does not save into unsafe_passwords_file in moccasin.toml

### DISCUSSION THREAD

**Discussion by Jon-Mervedel** [Cyfrin/moccasin-full-course-cu#33] [Q&A]
Hello all.

After multiple attempts, I have been unable to have my password saved. 

I have gone directly into the unsafe-passwords folder with echo "_password_" > _account_name_ and used cat _account_name_ to confirm. And I have set the unsafe_passwords_file in moccasin.toml to "~/.moccasin/unsafe-passwords/_account_name_" but I am still prompted.

Any clue?

**Comment by EngrPips** [comment]
Honestly, I will say don't sweat over this as that is not even a safe practice to start with, and entering the password to process your transaction isn't a stress as far as I am concerned. So I will say stick to the prompting and like that, you will be playing it more safe.

**Reply by s3bc40** [reply]
Yeah, you can follow along with the prompting, it is safer. It should not stop your progression. 

But if you want to compare your toml:
```toml
[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
prompt_live = false
default_account_name = "<YOUR_ACCOUNT_NAME>"
unsafe_password_file = "~/.moccasin/unsafe-passwords/<YOUR_ACCOUNT_NAME>" # ONLY FOR DUMMY ACCOUNT
```

Double-check your path to `.moccasin/unsafe-passwords` and your toml config.
